<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.305.28" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.8" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.8" />
    <PackageReference Include="MailKit" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0-preview.2.24128.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0-preview.2.24128.5" />
    <PackageReference Include="Stripe.net" Version="43.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Application\Mriguel.Application.csproj" />
  </ItemGroup>

</Project>
