<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <UserSecretsId>93c7e173-8e33-4156-9c14-0ce74a1a28fb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.8" />
    <PackageReference Include="Hangfire.NetCore" Version="1.8.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0-preview.2.24128.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0-preview.2.24128.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0-preview.2.24128.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Application\Mriguel.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Identity\Mriguel.Identity.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure\Mriguel.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Persistence\Mriguel.Persistence.csproj" />
    <ProjectReference Include="..\SignalR\Mriguel.SignalR.csproj" />
  </ItemGroup>

</Project>
